version: "3.9"
services:
  goPlant:
    image: 
    ports:
      - "80:80"
    networks:
      - docker_network
    depends_on:
      - db
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=
    networks:
      - docker_network
networks:
  docker_network:
    driver: bridge
