apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-migration
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install 
    "helm.sh/hook-weight": "-10" 
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  DB_HOST: {{ include "goplant.fullname" . }}-postgresql
  DB_PORT: {{ .Values.postgresql.postgresqlPort | quote}}
  DB_NAME: {{ .Values.postgresql.postgresqlDatabase | quote}}
  DB_USERNAME: {{ .Values.postgresql.postgresqlUsername | quote}}
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword | quote}}
  APP_HOST: {{ .Values.app.host | quote}}
  APP_PORT: {{ .Values.app.port | quote}}